version: '2'

services:
    web:
        image: nginx:latest
        container_name: nginx-${PROJECT_NAME}
        ports:
            - "8080:80"
        volumes:
            - ./source:/source
            - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./l:/var/log/nginx
    php:
        container_name: php-${PROJECT_NAME}
        build: ./config/php
        environment:
            XDEBUG_CONFIG: remote_host=127.0.0.1
        volumes:
            - ./source:/source
    mysql:
      image: mysql:latest
      container_name: mysql-${PROJECT_NAME}
      ports:
        - "3306:3306"
      environment:
        - MYSQL_ROOT_PASSWORD=password

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin-${PROJECT_NAME}

      links:
        - mysql:db
      ports:
        - "8081:80"
      environment:
        - PMA_USER=root
        - PMA_PASSWORD=password
        - PHP_UPLOAD_MAX_FILESIZE=100MB